#Your chosen discord bot's token goes here. Don't share it with ANYONE.
bot-token: ""
#The Discord server to connect to. This setting helps when you have
#the same bot in multiple servers.
server-id: ""
#The channel to write to and read messages from.
channel-id: ""
# MESSAGE CUSTOMIZATION
# NOTE: {player} -> player name, {adv} -> advancement name
# {msg} -> message name
# & -> colour code operator (look up Bukkit colour codes for this)
# NOTE: For '&', formatting goes before colour. Won't work otherwise.
# This means that discord-msg needs to have the bold formatting code before
# some colour code, for e.g. &l&b works. &b&l won't.
# * * -> italicised; ** ** -> bold; *** *** -> mix of both
# look up Discord formatting for more!

# Message that will be sent from Discord to Minecraft
dc-chat-msg: "&l{player}:&r {msg}"

# Message that will be sent from Minecraft to Discord
mc-chat-msg: "**{player}:** {msg}"

# Following are for server start, stop and player join, quit, advancement messages
start-msg: "Server was **started**!âœ…"
stop-msg: "Server has been **stopped**.ğŸ›‘"
join-msg: "ğŸ“¥***{player}*** *just joined the server!*"
quit-msg: "ğŸ“¤***{player}*** *has left the server.*"
adv-msg: "â›ï¸***{player}*** *has completed the advancement* ***{adv}*** *!*"
dc-death-msg: "âš°ï¸***{player}*** *died!*"